// <auto-generated />
using DBKINOTEATR.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DBKINOTEATR.Migrations
{
    [DbContext(typeof(DBKINOTEATRContext))]
    [Migration("20210520191207_Ini")]
    partial class Ini
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DBKINOTEATR.Models.DOLJNOSTI", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NAIMENOVANIE_DOLJNOSTI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OBYAZANOSTI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OKLAD")
                        .HasColumnType("int");

                    b.Property<string>("TREBOVANIYA")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DOLJNOSTI");
                });

            modelBuilder.Entity("DBKINOTEATR.Models.SOTRUDNIKI", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FIO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pasportnie_danie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("phone_number")
                        .HasColumnType("bigint");

                    b.Property<string>("pol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("vozrast")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("SOTRUDNIKI");
                });
#pragma warning restore 612, 618
        }
    }
}
